package com.toxicplants.database.ui.screens.toxicgenera

data class ToxicGenus(
    val genus: String,
    val family: String,
    val commonNameEs: String,
    val speciesCount: Int,
    val toxicityNote: String,
    val gbifGenusKey: Long? = null,
)

object ToxicGeneraCatalog {
    val all = listOf(
        ToxicGenus("Aconitum", "Ranunculaceae", "Acónito", 948, "Alcaloides diterpénicos - Muy mortal", 3033662),
        ToxicGenus("Abrus", "Fabaceae", "Abrus", 18, "Abrina - Mortal, 1 semilla", 2972924),
        ToxicGenus("Adenium", "Apocynaceae", "Rosa del desierto", 12, "Glucósidos cardiotónicos", 3169815),
        ToxicGenus("Adonis", "Ranunculaceae", "Adonis", 32, "Cardiotónico", 3033293),
        ToxicGenus("Aesculus", "Sapindaceae", "Castaño de indias", 13, "Esculina", 3189813),
        ToxicGenus("Ageratina", "Asteraceae", "Ageratina", 330, "Tremetol", 3141259),
        ToxicGenus("Anagyris", "Fabaceae", "Altramuz del diablo", 2, "Citisina", null),
        ToxicGenus("Anemone", "Ranunculaceae", "Anémona", 172, "Protoanemonina", 3033255),
        ToxicGenus("Anthurium", "Araceae", "Anturio", 1143, "Oxalatos", 2862648),
        ToxicGenus("Arisaema", "Araceae", "Arisaema", 211, "Oxalatos", 2867129),
        ToxicGenus("Aristolochia", "Aristolochiaceae", "Aristoloquia", 550, "Ácido aristolóquico - Nefrotóxico", 2874038),
        ToxicGenus("Arum", "Araceae", "Aro", 33, "Oxalatos", 2871839),
        ToxicGenus("Asclepias", "Apocynaceae", "Asclepia", 215, "Cardenólidos", 3169828),
        ToxicGenus("Atropa", "Solanaceae", "Belladona", 4, "Tropanos - Mortal", 2928841),
        ToxicGenus("Baptisia", "Fabaceae", "Baptisia", 20, "Citisina", null),
        ToxicGenus("Brugmansia", "Solanaceae", "Floripondio", 8, "Escopolamina - Alucinógeno mortal", 2928862),
        ToxicGenus("Caladium", "Araceae", "Caladio", 12, "Oxalatos", 2867870),
        ToxicGenus("Cerbera", "Apocynaceae", "Cerbera", 6, "Cerberina - Mortal", null),
        ToxicGenus("Cestrum", "Solanaceae", "Cestrum", 250, "Saponinas / glucósidos", 2928611),
        ToxicGenus("Chelidonium", "Papaveraceae", "Celidonia", 1, "Alcaloides isoquinolínicos", 2888439),
        ToxicGenus("Cicuta", "Apiaceae", "Cicuta acuática", 4, "Cicutotoxina - Mortal", 3034521),
        ToxicGenus("Clematis", "Ranunculaceae", "Clemátide", 380, "Protoanemonina", 3033331),
        ToxicGenus("Clivia", "Amaryllidaceae", "Clivia", 6, "Licorina", null),
        ToxicGenus("Codiaeum", "Euphorbiaceae", "Crotón", 17, "Ésteres de forbol", null),
        ToxicGenus("Colchicum", "Colchicaceae", "Cólquico", 160, "Colchicina - Mortal", 2739556),
        ToxicGenus("Colocasia", "Araceae", "Taro", 16, "Oxalatos", 2867032),
        ToxicGenus("Conium", "Apiaceae", "Cicuta", 4, "Coniina - Mortal", 3034641),
        ToxicGenus("Convallaria", "Asparagaceae", "Lirio de los valles", 1, "Convallatoxina", 2767972),
        ToxicGenus("Coriaria", "Coriariaceae", "Roldón", 15, "Coriamirtina", 5380599),
        ToxicGenus("Cryptostegia", "Apocynaceae", "Cryptostegia", 2, "Cardenólidos", null),
        ToxicGenus("Cycas", "Cycadaceae", "Cica", 120, "Cicasina", 2683305),
        ToxicGenus("Cytisus", "Fabaceae", "Retama", 32, "Citisina / esparteína", 2964664),
        ToxicGenus("Daphne", "Thymelaeaceae", "Torvisco", 95, "Mezereína", 5426421),
        ToxicGenus("Datura", "Solanaceae", "Estramonio", 14, "Tropanos - Alucinógeno mortal", 2928763),
        ToxicGenus("Delphinium", "Ranunculaceae", "Espuela de caballero", 457, "Alcaloides diterpénicos", 3033703),
        ToxicGenus("Dictamnus", "Rutaceae", "Díctamo", 6, "Furocumarinas - Fototóxico", null),
        ToxicGenus("Dieffenbachia", "Araceae", "Dieffenbachia", 63, "Oxalatos", 2867422),
        ToxicGenus("Digitalis", "Plantaginaceae", "Dedalera", 26, "Digitálicos - Cardiotóxico mortal", 5414372),
        ToxicGenus("Echium", "Boraginaceae", "Viborera", 67, "Alcaloides pirrolizidínicos", 2925945),
        ToxicGenus("Erysimum", "Brassicaceae", "Alhelí", 270, "Cardenólidos", 3048393),
        ToxicGenus("Euonymus", "Celastraceae", "Bonetero", 142, "Evonina", 3169047),
        ToxicGenus("Euphorbia", "Euphorbiaceae", "Euforbia", 2046, "Ésteres de forbol", 3069811),
        ToxicGenus("Galanthus", "Amaryllidaceae", "Campanilla de invierno", 20, "Galantamina / licorina", 2855327),
        ToxicGenus("Gelsemium", "Gelsemiaceae", "Jazmín de Carolina", 3, "Gelsemina - Mortal", null),
        ToxicGenus("Gloriosa", "Colchicaceae", "Gloriosa", 12, "Colchicina", 2739641),
        ToxicGenus("Hedera", "Araliaceae", "Hiedra", 12, "Hederasaponinas", 3034897),
        ToxicGenus("Helleborus", "Ranunculaceae", "Eléboro", 22, "Heleboreína", 3033308),
        ToxicGenus("Hemerocallis", "Asphodelaceae", "Lirio de día", 17, "Nefrotóxico en gatos", null),
        ToxicGenus("Hippeastrum", "Amaryllidaceae", "Amarilis", 110, "Licorina", 2855437),
        ToxicGenus("Hippomane", "Euphorbiaceae", "Manzanillo", 3, "Forbol - Mortal", null),
        ToxicGenus("Hyoscyamus", "Solanaceae", "Beleño", 20, "Hiosciamina", 2928752),
        ToxicGenus("Ilex", "Aquifoliaceae", "Acebo", 585, "Ilicina", 3169879),
        ToxicGenus("Jatropha", "Euphorbiaceae", "Jatrofa", 190, "Curcina", 3063526),
        ToxicGenus("Kalmia", "Ericaceae", "Kalmia", 10, "Grayanotoxinas", 2882819),
        ToxicGenus("Laburnum", "Fabaceae", "Lluvia de oro", 2, "Citisina", 2962865),
        ToxicGenus("Lantana", "Verbenaceae", "Lantana", 150, "Lantadenos", 2925307),
        ToxicGenus("Ligustrum", "Oleaceae", "Aligustre", 45, "Ligustrina", 3172286),
        ToxicGenus("Lolium", "Poaceae", "Ballico", 27, "Temulina", 2706228),
        ToxicGenus("Lupinus", "Fabaceae", "Altramuz", 620, "Lupinina / esparteína", 2964192),
        ToxicGenus("Mandragora", "Solanaceae", "Mandrágora", 5, "Tropanos", 2928856),
        ToxicGenus("Melia", "Meliaceae", "Melia", 3, "Meliatoxinas", 3190459),
        ToxicGenus("Monstera", "Araceae", "Costilla de Adán", 37, "Oxalatos", 2868239),
        ToxicGenus("Narcissus", "Amaryllidaceae", "Narciso", 52, "Licorina", 2858643),
        ToxicGenus("Nerium", "Apocynaceae", "Adelfa", 3, "Oleandrina - Mortal", 3169867),
        ToxicGenus("Nicotiana", "Solanaceae", "Tabaco", 79, "Nicotina", 2928488),
        ToxicGenus("Oenanthe", "Apiaceae", "Felándrio", 40, "Enantotoxina", 3034534),
        ToxicGenus("Ornithogalum", "Asparagaceae", "Leche de gallina", 180, "Cardenólidos", 2769646),
        ToxicGenus("Paris", "Melanthiaceae", "Uva de zorro", 27, "Paristifnina", null),
        ToxicGenus("Philodendron", "Araceae", "Filodendro", 524, "Oxalatos", 2867771),
        ToxicGenus("Phytolacca", "Phytolaccaceae", "Fitolaca", 25, "Fitolacatoxina", 3084064),
        ToxicGenus("Ranunculus", "Ranunculaceae", "Ranúnculo", 1700, "Protoanemonina", 3033494),
        ToxicGenus("Rhododendron", "Ericaceae", "Rododendro", 1076, "Grayanotoxinas", 2882803),
        ToxicGenus("Ricinus", "Euphorbiaceae", "Ricino", 1, "Ricina - Mortal", 3063467),
        ToxicGenus("Robinia", "Fabaceae", "Falsa acacia", 10, "Robina / fasina", 2962354),
        ToxicGenus("Senecio", "Asteraceae", "Senecio", 1494, "Pirrolizidínicos - Hepatotóxico", 3109349),
        ToxicGenus("Solanum", "Solanaceae", "Solano", 1393, "Solanina", 2930334),
        ToxicGenus("Spartium", "Fabaceae", "Retama", 1, "Esparteína / citisina", null),
        ToxicGenus("Strophanthus", "Apocynaceae", "Estrofanto", 38, "Estrofantina - Cardiotóxico", 3169877),
        ToxicGenus("Strychnos", "Loganiaceae", "Nuez vómica", 207, "Estricnina - Mortal", 3169910),
        ToxicGenus("Taxus", "Taxaceae", "Tejo", 9, "Taxina - Mortal", 2684907),
        ToxicGenus("Thevetia", "Apocynaceae", "Thevetia", 8, "Thevetina - Cardiotóxico", 3169933),
        ToxicGenus("Veratrum", "Melanthiaceae", "Verdegambre", 27, "Veratrina", 2741984),
        ToxicGenus("Viscum", "Santalaceae", "Muérdago", 150, "Viscotoxinas", 4002432),
        ToxicGenus("Wisteria", "Fabaceae", "Glicinia", 10, "Wisterina", 2962419),
    ).distinctBy { it.genus }.sortedBy { it.genus }
}
