package com.toxicplants.database

/** Catálogo de respaldo si el asset lichens.json no está disponible en el APK. */
object LichenCatalogFallback {
    val items: List<LichenEntity> = listOf(
        LichenEntity(
            id = 1,
            commonName = "Liquen de los lobos",
            scientificName = "Letharia vulpina",
            family = "Parmeliaceae",
            toxicityLevel = "Alta",
            syndrome = "Vulpínico",
            toxicCompounds = "Ácido vulpínico y derivados pulvinicos",
            onsetTime = "30 min-6 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal, debilidad; en animales se describen cuadros graves tras ingestión.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Coníferas de montaña, ramas y cortezas ácidas.",
            geographicDistribution = "Europa, Norteamérica y regiones montanas del hemisferio norte",
            confusions = "Usnea amarillentas, Vulpicida pinastri",
            firstAid = "Evitar consumo; si hay ingesta accidental, conservar muestra y consultar toxicología.",
            treatment = "Tratamiento sintomático, hidratación y vigilancia clínica.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = true,
            isFavorite = false,
        ),
        LichenEntity(
            id = 2,
            commonName = "Vulpicida de pino",
            scientificName = "Vulpicida pinastri",
            family = "Parmeliaceae",
            toxicityLevel = "Alta",
            syndrome = "Vulpínico",
            toxicCompounds = "Ácido vulpínico y derivados pulvinicos",
            onsetTime = "30 min-6 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal, debilidad; en animales se describen cuadros graves tras ingestión.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas de coníferas y madera muerta en zonas frías.",
            geographicDistribution = "Europa, Asia y Norteamérica boreal",
            confusions = "Cetraria, Letharia, líquenes amarillos",
            firstAid = "Evitar consumo; si hay ingesta accidental, conservar muestra y consultar toxicología.",
            treatment = "Tratamiento sintomático, hidratación y vigilancia clínica.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = true,
            isFavorite = false,
        ),
        LichenEntity(
            id = 3,
            commonName = "Vulpicida canadiense",
            scientificName = "Vulpicida canadensis",
            family = "Parmeliaceae",
            toxicityLevel = "Alta",
            syndrome = "Vulpínico",
            toxicCompounds = "Ácido vulpínico y derivados pulvinicos",
            onsetTime = "30 min-6 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal, debilidad; en animales se describen cuadros graves tras ingestión.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Ramas de coníferas en bosques boreales.",
            geographicDistribution = "Norteamérica septentrional",
            confusions = "Vulpicida pinastri, Letharia",
            firstAid = "Evitar consumo; si hay ingesta accidental, conservar muestra y consultar toxicología.",
            treatment = "Tratamiento sintomático, hidratación y vigilancia clínica.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = true,
            isFavorite = false,
        ),
        LichenEntity(
            id = 4,
            commonName = "Bryoria tortuosa",
            scientificName = "Bryoria tortuosa",
            family = "Parmeliaceae",
            toxicityLevel = "Alta",
            syndrome = "Vulpínico",
            toxicCompounds = "Ácido vulpínico y derivados pulvinicos",
            onsetTime = "30 min-6 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal, debilidad; en animales se describen cuadros graves tras ingestión.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Ramas de coníferas en bosques húmedos montanos.",
            geographicDistribution = "Norteamérica y Eurasia boreal",
            confusions = "Bryoria comestibles tradicionales",
            firstAid = "Evitar consumo; si hay ingesta accidental, conservar muestra y consultar toxicología.",
            treatment = "Tratamiento sintomático, hidratación y vigilancia clínica.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = true,
            isFavorite = false,
        ),
        LichenEntity(
            id = 5,
            commonName = "Cetraria pinastri",
            scientificName = "Cetraria pinastri",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Vulpínico",
            toxicCompounds = "Ácido vulpínico y derivados pulvinicos",
            onsetTime = "30 min-6 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal, debilidad; en animales se describen cuadros graves tras ingestión.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Corteza y madera de coníferas.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Vulpicida pinastri",
            firstAid = "Evitar consumo; si hay ingesta accidental, conservar muestra y consultar toxicología.",
            treatment = "Tratamiento sintomático, hidratación y vigilancia clínica.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 6,
            commonName = "Usnea común",
            scientificName = "Usnea spp.",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Úsnico/hepatotóxico",
            toxicCompounds = "Ácido úsnico, atranorina y ácidos liquénicos relacionados",
            onsetTime = "Horas-días",
            symptoms = "Molestias digestivas; exposición concentrada a ácido úsnico se ha asociado a hepatotoxicidad. Contacto puede irritar piel en sensibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Ramas de árboles en ambientes limpios y húmedos.",
            geographicDistribution = "Cosmopolita",
            confusions = "Barbas de viejo y otros líquenes fruticulosos",
            firstAid = "No ingerir preparados no controlados; consultar si hay dolor abdominal, ictericia, orina oscura o malestar persistente.",
            treatment = "Soporte médico, control hepático si hay ingesta significativa.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 7,
            commonName = "Usnea barbata",
            scientificName = "Usnea barbata",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Úsnico/hepatotóxico",
            toxicCompounds = "Ácido úsnico, atranorina y ácidos liquénicos relacionados",
            onsetTime = "Horas-días",
            symptoms = "Molestias digestivas; exposición concentrada a ácido úsnico se ha asociado a hepatotoxicidad. Contacto puede irritar piel en sensibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Bosques húmedos sobre ramas.",
            geographicDistribution = "Europa y Asia",
            confusions = "Usnea spp.",
            firstAid = "No ingerir preparados no controlados; consultar si hay dolor abdominal, ictericia, orina oscura o malestar persistente.",
            treatment = "Soporte médico, control hepático si hay ingesta significativa.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 8,
            commonName = "Usnea filipendula",
            scientificName = "Usnea filipendula",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Úsnico/hepatotóxico",
            toxicCompounds = "Ácido úsnico, atranorina y ácidos liquénicos relacionados",
            onsetTime = "Horas-días",
            symptoms = "Molestias digestivas; exposición concentrada a ácido úsnico se ha asociado a hepatotoxicidad. Contacto puede irritar piel en sensibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Coníferas y frondosas en bosques húmedos.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Usnea similares",
            firstAid = "No ingerir preparados no controlados; consultar si hay dolor abdominal, ictericia, orina oscura o malestar persistente.",
            treatment = "Soporte médico, control hepático si hay ingesta significativa.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 9,
            commonName = "Usnea hirta",
            scientificName = "Usnea hirta",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Úsnico/hepatotóxico",
            toxicCompounds = "Ácido úsnico, atranorina y ácidos liquénicos relacionados",
            onsetTime = "Horas-días",
            symptoms = "Molestias digestivas; exposición concentrada a ácido úsnico se ha asociado a hepatotoxicidad. Contacto puede irritar piel en sensibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas y madera expuesta.",
            geographicDistribution = "Europa y Norteamérica",
            confusions = "Usnea cortas",
            firstAid = "No ingerir preparados no controlados; consultar si hay dolor abdominal, ictericia, orina oscura o malestar persistente.",
            treatment = "Soporte médico, control hepático si hay ingesta significativa.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 10,
            commonName = "Ramalina farinacea",
            scientificName = "Ramalina farinacea",
            family = "Ramalinaceae",
            toxicityLevel = "Moderada",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Ramas y corteza de frondosas.",
            geographicDistribution = "Europa, África norte y América",
            confusions = "Evernia prunastri",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 11,
            commonName = "Ramalina fraxinea",
            scientificName = "Ramalina fraxinea",
            family = "Ramalinaceae",
            toxicityLevel = "Moderada",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Troncos y ramas de árboles viejos.",
            geographicDistribution = "Europa y Asia templada",
            confusions = "Ramalina fastigiata",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 12,
            commonName = "Evernia prunastri",
            scientificName = "Evernia prunastri",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Corteza de robles y frutales.",
            geographicDistribution = "Europa y regiones templadas",
            confusions = "Pseudevernia furfuracea",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 13,
            commonName = "Pseudevernia furfuracea",
            scientificName = "Pseudevernia furfuracea",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Úsnico/hepatotóxico",
            toxicCompounds = "Ácido úsnico, atranorina y ácidos liquénicos relacionados",
            onsetTime = "Horas-días",
            symptoms = "Molestias digestivas; exposición concentrada a ácido úsnico se ha asociado a hepatotoxicidad. Contacto puede irritar piel en sensibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Coníferas y frondosas; frecuente en montaña.",
            geographicDistribution = "Europa, Asia y Norteamérica",
            confusions = "Evernia prunastri",
            firstAid = "No ingerir preparados no controlados; consultar si hay dolor abdominal, ictericia, orina oscura o malestar persistente.",
            treatment = "Soporte médico, control hepático si hay ingesta significativa.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 14,
            commonName = "Hypogymnia physodes",
            scientificName = "Hypogymnia physodes",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas ácidas de árboles y ramas.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Hypogymnia tubulosa",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 15,
            commonName = "Hypogymnia tubulosa",
            scientificName = "Hypogymnia tubulosa",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Ramas en bosques húmedos.",
            geographicDistribution = "Europa y Norteamérica",
            confusions = "Hypogymnia physodes",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 16,
            commonName = "Parmelia sulcata",
            scientificName = "Parmelia sulcata",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas y rocas, común en zonas templadas.",
            geographicDistribution = "Cosmopolita templado",
            confusions = "Parmelia saxatilis",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 17,
            commonName = "Parmelia saxatilis",
            scientificName = "Parmelia saxatilis",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas silíceas y cortezas.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Parmelia sulcata",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 18,
            commonName = "Flavoparmelia caperata",
            scientificName = "Flavoparmelia caperata",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas de frondosas y rocas.",
            geographicDistribution = "Cosmopolita templado",
            confusions = "Parmotrema perlatum",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 19,
            commonName = "Parmotrema perlatum",
            scientificName = "Parmotrema perlatum",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas y rocas en ambientes húmedos.",
            geographicDistribution = "Regiones templadas y tropicales",
            confusions = "Flavoparmelia",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 20,
            commonName = "Xanthoria parietina",
            scientificName = "Xanthoria parietina",
            family = "Teloschistaceae",
            toxicityLevel = "Baja",
            syndrome = "Fototóxico",
            toxicCompounds = "Antraquinonas y pigmentos fenólicos fotoreactivos",
            onsetTime = "Horas tras contacto/luz",
            symptoms = "Irritación cutánea y posible fotosensibilidad en personas susceptibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas enriquecidas en nitrógeno y rocas costeras.",
            geographicDistribution = "Cosmopolita",
            confusions = "Caloplaca, Teloschistes",
            firstAid = "Lavar zona y evitar exposición solar si hay irritación.",
            treatment = "Tratamiento sintomático de dermatitis.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 21,
            commonName = "Teloschistes chrysophthalmus",
            scientificName = "Teloschistaceae sp.",
            family = "Teloschistaceae",
            toxicityLevel = "Baja",
            syndrome = "Fototóxico",
            toxicCompounds = "Antraquinonas y pigmentos fenólicos fotoreactivos",
            onsetTime = "Horas tras contacto/luz",
            symptoms = "Irritación cutánea y posible fotosensibilidad en personas susceptibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Ramas expuestas y matorral mediterráneo.",
            geographicDistribution = "Europa, América, África",
            confusions = "Xanthoria fruticulosa",
            firstAid = "Lavar zona y evitar exposición solar si hay irritación.",
            treatment = "Tratamiento sintomático de dermatitis.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 22,
            commonName = "Variospora flavescens",
            scientificName = "Variospora flavescens",
            family = "Teloschistaceae",
            toxicityLevel = "Baja",
            syndrome = "Fototóxico",
            toxicCompounds = "Antraquinonas y pigmentos fenólicos fotoreactivos",
            onsetTime = "Horas tras contacto/luz",
            symptoms = "Irritación cutánea y posible fotosensibilidad en personas susceptibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas calcáreas soleadas.",
            geographicDistribution = "Europa",
            confusions = "Caloplaca amarillas",
            firstAid = "Lavar zona y evitar exposición solar si hay irritación.",
            treatment = "Tratamiento sintomático de dermatitis.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 23,
            commonName = "Candelaria concolor",
            scientificName = "Candelariaceae",
            family = "Candelariaceae",
            toxicityLevel = "Baja",
            syndrome = "Fototóxico",
            toxicCompounds = "Antraquinonas y pigmentos fenólicos fotoreactivos",
            onsetTime = "Horas tras contacto/luz",
            symptoms = "Irritación cutánea y posible fotosensibilidad en personas susceptibles.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas ricas en nutrientes.",
            geographicDistribution = "Cosmopolita",
            confusions = "Xanthoria pequeñas",
            firstAid = "Lavar zona y evitar exposición solar si hay irritación.",
            treatment = "Tratamiento sintomático de dermatitis.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 24,
            commonName = "Chrysothrix candelaris",
            scientificName = "Chrysothrix candelaris",
            family = "Chrysotrichaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Polvo amarillo sobre cortezas y madera.",
            geographicDistribution = "Europa y América",
            confusions = "Candelaria, Lepraria",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 25,
            commonName = "Lepraria incana",
            scientificName = "Lepraria incana",
            family = "Stereocaulaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas, rocas y muros sombríos.",
            geographicDistribution = "Cosmopolita",
            confusions = "Polvos liquénicos verdes",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 26,
            commonName = "Cladonia rangiferina",
            scientificName = "Cladonia rangiferina",
            family = "Cladoniaceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Suelos ácidos, tundra y pinares.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Cladonia arbuscula",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 27,
            commonName = "Cladonia arbuscula",
            scientificName = "Cladonia arbuscula",
            family = "Cladoniaceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Brezales y pinares pobres.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Cladonia rangiferina",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 28,
            commonName = "Cladonia stellaris",
            scientificName = "Cladonia stellaris",
            family = "Cladoniaceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Tundra y bosques boreales.",
            geographicDistribution = "Ártico y boreal",
            confusions = "Cladonia alpestris",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 29,
            commonName = "Cladonia uncialis",
            scientificName = "Cladonia uncialis",
            family = "Cladoniaceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Suelos ácidos y arenosos.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Cladonia arbuscula",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 30,
            commonName = "Cetraria islandica",
            scientificName = "Cetraria islandica",
            family = "Parmeliaceae",
            toxicityLevel = "Moderada",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Suelos fríos de montaña y tundra.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Cetraria ericetorum",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 31,
            commonName = "Flavocetraria nivalis",
            scientificName = "Flavocetraria nivalis",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Tundra y alta montaña.",
            geographicDistribution = "Ártico-alpino",
            confusions = "Cetraria islandica",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 32,
            commonName = "Flavocetraria cucullata",
            scientificName = "Flavocetraria cucullata",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Tundra y regiones alpinas.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Flavocetraria nivalis",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 33,
            commonName = "Alectoria sarmentosa",
            scientificName = "Alectoria sarmentosa",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Bosques húmedos de coníferas.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Bryoria",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 34,
            commonName = "Lobaria pulmonaria",
            scientificName = "Lobaria pulmonaria",
            family = "Lobariaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Bosques húmedos maduros sobre corteza.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Lobaria amplissima",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 35,
            commonName = "Peltigera canina",
            scientificName = "Peltigera canina",
            family = "Peltigeraceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Suelos musgosos y taludes.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Peltigera rufescens",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 36,
            commonName = "Peltigera rufescens",
            scientificName = "Peltigera rufescens",
            family = "Peltigeraceae",
            toxicityLevel = "Baja",
            syndrome = "Gastrointestinal",
            toxicCompounds = "Ácidos liquénicos amargos e irritantes",
            onsetTime = "1-8 h",
            symptoms = "Náuseas, vómitos, diarrea, dolor abdominal y malestar.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Suelos secos y calizos.",
            geographicDistribution = "Europa y Asia",
            confusions = "Peltigera canina",
            firstAid = "No inducir vómito; hidratar y consultar si síntomas intensos.",
            treatment = "Rehidratación y control sintomático.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 37,
            commonName = "Umbilicaria mammulata",
            scientificName = "Umbilicaria mammulata",
            family = "Umbilicariaceae",
            toxicityLevel = "Baja",
            syndrome = "Oxalatos/metales",
            toxicCompounds = "Oxalatos, ácidos orgánicos y posible bioacumulación de metales",
            onsetTime = "Horas",
            symptoms = "Irritación digestiva, náuseas; riesgo mayor por contaminación ambiental o consumo repetido.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas silíceas expuestas.",
            geographicDistribution = "Norteamérica",
            confusions = "Umbilicaria comestibles tras procesado",
            firstAid = "No consumir líquenes de zonas contaminadas; consultar si hay síntomas.",
            treatment = "Soporte e hidratación.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 38,
            commonName = "Lasallia pustulata",
            scientificName = "Lasallia pustulata",
            family = "Umbilicariaceae",
            toxicityLevel = "Baja",
            syndrome = "Oxalatos/metales",
            toxicCompounds = "Oxalatos, ácidos orgánicos y posible bioacumulación de metales",
            onsetTime = "Horas",
            symptoms = "Irritación digestiva, náuseas; riesgo mayor por contaminación ambiental o consumo repetido.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas silíceas soleadas.",
            geographicDistribution = "Europa y Asia",
            confusions = "Umbilicaria",
            firstAid = "No consumir líquenes de zonas contaminadas; consultar si hay síntomas.",
            treatment = "Soporte e hidratación.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 39,
            commonName = "Rhizocarpon geographicum",
            scientificName = "Rhizocarpon geographicum",
            family = "Rhizocarpaceae",
            toxicityLevel = "Baja",
            syndrome = "Oxalatos/metales",
            toxicCompounds = "Oxalatos, ácidos orgánicos y posible bioacumulación de metales",
            onsetTime = "Horas",
            symptoms = "Irritación digestiva, náuseas; riesgo mayor por contaminación ambiental o consumo repetido.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas ácidas de montaña.",
            geographicDistribution = "Cosmopolita frío",
            confusions = "Acarospora, líquenes crustáceos",
            firstAid = "No consumir líquenes de zonas contaminadas; consultar si hay síntomas.",
            treatment = "Soporte e hidratación.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 40,
            commonName = "Stereocaulon paschale",
            scientificName = "Stereocaulon paschale",
            family = "Stereocaulaceae",
            toxicityLevel = "Baja",
            syndrome = "Oxalatos/metales",
            toxicCompounds = "Oxalatos, ácidos orgánicos y posible bioacumulación de metales",
            onsetTime = "Horas",
            symptoms = "Irritación digestiva, náuseas; riesgo mayor por contaminación ambiental o consumo repetido.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Suelos pobres, rocas y tundra.",
            geographicDistribution = "Hemisferio norte",
            confusions = "Cladonia",
            firstAid = "No consumir líquenes de zonas contaminadas; consultar si hay síntomas.",
            treatment = "Soporte e hidratación.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 41,
            commonName = "Xanthoparmelia conspersa",
            scientificName = "Xanthoparmelia conspersa",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas silíceas soleadas.",
            geographicDistribution = "Europa y Norteamérica",
            confusions = "Xanthoparmelia stenophylla",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 42,
            commonName = "Xanthoparmelia chlorochroa",
            scientificName = "Xanthoparmelia chlorochroa",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Suelos áridos y praderas secas.",
            geographicDistribution = "Norteamérica occidental",
            confusions = "Xanthoparmelia terrestres",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 43,
            commonName = "Xanthoparmelia cumberlandia",
            scientificName = "Xanthoparmelia cumberlandia",
            family = "Parmeliaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas y suelos secos.",
            geographicDistribution = "Norteamérica",
            confusions = "Xanthoparmelia",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 44,
            commonName = "Physcia adscendens",
            scientificName = "Physcia adscendens",
            family = "Physciaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas enriquecidas y muros.",
            geographicDistribution = "Cosmopolita",
            confusions = "Physcia tenella",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 45,
            commonName = "Physconia distorta",
            scientificName = "Physconia distorta",
            family = "Physciaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Cortezas de árboles en zonas templadas.",
            geographicDistribution = "Europa y Asia",
            confusions = "Physcia",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 46,
            commonName = "Diploicia canescens",
            scientificName = "Diploicia canescens",
            family = "Caliciaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Muros, rocas y cortezas.",
            geographicDistribution = "Europa occidental y mediterránea",
            confusions = "Physcia claras",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 47,
            commonName = "Ochrolechia parella",
            scientificName = "Ochrolechia parella",
            family = "Ochrolechiaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas silíceas y costeras.",
            geographicDistribution = "Europa atlántica",
            confusions = "Lecanora",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 48,
            commonName = "Lecanora muralis",
            scientificName = "Lecanora muralis",
            family = "Lecanoraceae",
            toxicityLevel = "Baja",
            syndrome = "Oxalatos/metales",
            toxicCompounds = "Oxalatos, ácidos orgánicos y posible bioacumulación de metales",
            onsetTime = "Horas",
            symptoms = "Irritación digestiva, náuseas; riesgo mayor por contaminación ambiental o consumo repetido.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Muros, cemento y rocas urbanas.",
            geographicDistribution = "Cosmopolita",
            confusions = "Lecanora rupícolas",
            firstAid = "No consumir líquenes de zonas contaminadas; consultar si hay síntomas.",
            treatment = "Soporte e hidratación.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 49,
            commonName = "Graphis scripta",
            scientificName = "Graphis scripta",
            family = "Graphidaceae",
            toxicityLevel = "Baja",
            syndrome = "Irritante/alergénico",
            toxicCompounds = "Atranorina, cloroatranorina, ácidos depsídicos y depsidonas",
            onsetTime = "Minutos-horas en contacto; horas si se ingiere",
            symptoms = "Dermatitis de contacto, picor, enrojecimiento, irritación ocular o digestiva leve.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Corteza lisa de hayas y avellanos.",
            geographicDistribution = "Europa y Norteamérica",
            confusions = "Graphis similares",
            firstAid = "Lavar piel/ojos con agua; evitar nuevo contacto; consultar si hay reacción extensa.",
            treatment = "Tratamiento sintomático, antihistamínicos/corticoides tópicos según criterio sanitario.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
        LichenEntity(
            id = 50,
            commonName = "Diploschistes scruposus",
            scientificName = "Diploschistes scruposus",
            family = "Diploschistaceae",
            toxicityLevel = "Baja",
            syndrome = "Oxalatos/metales",
            toxicCompounds = "Oxalatos, ácidos orgánicos y posible bioacumulación de metales",
            onsetTime = "Horas",
            symptoms = "Irritación digestiva, náuseas; riesgo mayor por contaminación ambiental o consumo repetido.",
            description = "Liquen con compuestos bioactivos potencialmente irritantes o tóxicos. La identificación de líquenes requiere lupa, pruebas químicas y experiencia; no se recomienda su consumo.",
            habitat = "Rocas silíceas y suelos.",
            geographicDistribution = "Cosmopolita",
            confusions = "Líquenes crustáceos grises",
            firstAid = "No consumir líquenes de zonas contaminadas; consultar si hay síntomas.",
            treatment = "Soporte e hidratación.",
            notes = "Información divulgativa. Muchos líquenes acumulan contaminantes ambientales; evitar ingerirlos o usarlos en remedios caseros.",
            imageUrl = "",
            isHighRisk = false,
            isFavorite = false,
        ),
    )
}